# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(True)
        font.setUnderline(True)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setGeometry(QtCore.QRect(12, 160, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input.setFont(font)
        self.input.setInputMask("")
        self.input.setText("")
        self.input.setObjectName("input")
        self.input.setEnabled(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 251, 16))
        self.label_2.setObjectName("label_2")
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setGeometry(QtCore.QRect(40, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.check_btn.setFont(font)
        self.check_btn.setObjectName("check_btn")
        self.check_btn.setEnabled(False)
        self.parse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.parse_btn.setGeometry(QtCore.QRect(220, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.parse_btn.setFont(font)
        self.parse_btn.setObjectName("parse_btn")
        self.parse_btn.setEnabled(False)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 510, 361, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 290, 361, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.get_parser = QtWidgets.QComboBox(self.centralwidget)
        self.get_parser.setGeometry(QtCore.QRect(210, 80, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.get_parser.setFont(font)
        self.get_parser.setEditable(False)
        self.get_parser.setCurrentText("")
        self.get_parser.setObjectName("get_parser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 181, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parser"))
        self.label.setText(_translate("MainWindow", "Simple Parser"))
        self.label_2.setText(_translate("MainWindow", "Enter the job title you are looking for:"))
        self.check_btn.setText(_translate("MainWindow", "Check"))
        self.parse_btn.setText(_translate("MainWindow", "Parse"))
        self.label_3.setText(_translate("MainWindow", "Select the parser you need:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
